### PR TITLE
Feature/45 auto retry

### PR DESCRIPTION
**Pull request by tott**
- Disable sites using rss/xml pulling methods after configured amount of failed attempts
- Implement logging and event triggers in rss client
- remove legacy logging methods from xml client
- Creation of a class to handle sticky admin notices and also can deal with summarizing notices. This will be used in further development and is currently implemented to notify when a site was disabled due to many failures.
- preview site status in site list
- sanitize text fields in save_settings method
- convert spaces to tabs in rss client

this should resolve https://github.com/Automattic/syndication/issues/45

With the restructuring rewrite logging, events and notifications will be rolled out throughout the whole plugin structure.

### CODE REVIEW

**Comment by joshbetz** [comment]
@tott It looks like this just adds more logging and notifications. Am I missing something?

**Comment by tott** [comment]
@joshbetz this also now implements the necessary code to disable a site after a certain amount of failed attempts (configurable in config section) and adds an admin notice when this happens. Would you like to add further functionality to this?

**Comment by joshbetz** [comment]
@tott Yeah, the point of #45 is to add auto retry failed syndications. I don't think we can close it out without implementing that.

**Comment by tott** [comment]
That's confusing. In https://github.com/Automattic/syndication/issues/45#issuecomment-71207151 you stated

<quote>The logging framework looks cool. I guess the next step is to automatically retry (or disable on too many failures).</quote>

I obviously went with the "disable on too many failures" approach.

I'm fine with putting in a auto-retry feature if you let me know how you would like this to look like. Should I just trigger the same sync for the source right away via cron or a async http call to an ajax endpoint in case I detect a failure, or do you have anything else in mind?

Putting either approach in should be pretty straight forward now, you just need to let me know what's your preferred method.

**Comment by joshbetz** [comment]
Looks great. @jamesmehorter the commit messages were super helpful. Thanks!

**Pull request merged**
